### ISSUE TITLE
Add Typescript typings

### ISSUE THREAD

**Issue by diggerzl** [Valeronlol/express-json-rpc-router#1]

**Comment by Valeronlol** [comment]
Hey!
Could you explain in more detail what typings are you talking about? Did you mean "*.d.ts" TS typing?
Thanks for the comment!

**Comment by diggerzl** [comment]
Yep. It would be great

**Comment by Valeronlol** [comment]
https://github.com/Valeronlol/express-json-rpc-router/commit/a0ff38b27be8d20fa7242c08e2cc2fa33cc8d6be
Hey, I'm not sure i did it right. Because i'm not working with TS. PLease check it.
